### ISSUE TITLE
Support Layoutable properties

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Windows.Forms#110]

**Comment by Fr33dan** [comment]
I wanted to do something productive this morning and thought I would give this a whack. ToolStripMenuItemTarget and MessageBoxTarget's already support them, FormControlTarget was trivial to update, but layoutable properties has some larger implications for the RichTextBoxTarget.

RichTextBoxTarget was designed with the presumption that each target would specify a single RichTextBox. If the control and form name are Layout's instead of fixed strings, there is the possibility that the layout could render differently each time the same target is used and the 1 to 1 contract of target to RichTextBox is broken.

The target can still be reworked to find/create the appropriate RichTextBox on each log call, but this is a significant change to functionality.

The object references to the target's form and RichTextBox would have to be removed, as well as the static functions to find RichTextBoxTarget from a RichTextBox. The tests rely on these and would have to be reworked and could impact any users who might be using these.

I'm inclined to say it's worth it to add the flexibility of layoutable properties, but given y'alls rigorous testing strategy, maintaining compatibility could be a higher priority.

**Comment by 304NotModified** [comment]
> The target can still be reworked to find/create the appropriate RichTextBox on each log call, but this is a significant change to functionality.

We could still use layouts, but only support them when doing a new initialize or something like that.

**Comment by 304NotModified** [comment]
> I wanted to do something productive this morning and thought I would give this a whack. ToolStripMenuItemTarget and MessageBoxTarget's already support them, FormControlTarget was trivial to update, but layoutable properties has some larger implications for the RichTextBoxTarget.

Thanks for that!
